spring.application.name=app

# Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/checkpointz_db
spring.datasource.username=root
spring.datasource.password=

# O JPA cria as tabelas automaticamente para você
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true